export const CLAIM_STATES = {
  DRAFT: 'Draft',
  AI_REVIEWING: 'AI Reviewing',
  READY_FOR_SUBMISSION: 'Ready For Submission',
  SUBMITTED: 'Submitted',
  PRE_SUBMISSION_QA: 'AI Pre-Validation',
  INSURANCE_REVIEW: 'Insurance Review',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  CORRECTION_IN_PROGRESS: 'Correction In Progress',
  RESUBMITTED: 'Resubmitted',
  REIMBURSED: 'Reimbursed',
  CLOSED: 'Closed',
};

const ALLOWED_TRANSITIONS = {
  [CLAIM_STATES.DRAFT]: [CLAIM_STATES.AI_REVIEWING, CLAIM_STATES.READY_FOR_SUBMISSION],
  [CLAIM_STATES.AI_REVIEWING]: [CLAIM_STATES.READY_FOR_SUBMISSION, CLAIM_STATES.DRAFT],
  [CLAIM_STATES.READY_FOR_SUBMISSION]: [CLAIM_STATES.SUBMITTED],
  [CLAIM_STATES.SUBMITTED]: [CLAIM_STATES.INSURANCE_REVIEW, CLAIM_STATES.REJECTED],
  [CLAIM_STATES.PRE_SUBMISSION_QA]: [CLAIM_STATES.INSURANCE_REVIEW, CLAIM_STATES.REJECTED],
  [CLAIM_STATES.INSURANCE_REVIEW]: [CLAIM_STATES.APPROVED, CLAIM_STATES.REJECTED],
  [CLAIM_STATES.APPROVED]: [CLAIM_STATES.REIMBURSED, CLAIM_STATES.CLOSED],
  [CLAIM_STATES.REJECTED]: [CLAIM_STATES.CORRECTION_IN_PROGRESS],
  [CLAIM_STATES.CORRECTION_IN_PROGRESS]: [CLAIM_STATES.RESUBMITTED],
  [CLAIM_STATES.RESUBMITTED]: [CLAIM_STATES.INSURANCE_REVIEW, CLAIM_STATES.REJECTED],
  [CLAIM_STATES.REIMBURSED]: [CLAIM_STATES.CLOSED],
  [CLAIM_STATES.CLOSED]: [],
};

export function canTransition(currentStage, nextStage) {
  const allowed = ALLOWED_TRANSITIONS[currentStage] || [];
  return allowed.includes(nextStage);
}

export function getNextValidStages(currentStage) {
  return ALLOWED_TRANSITIONS[currentStage] || [];
}
